title: Prilik Writes About Tech
author: Daniel Prilik
email: daniel@prilik.com
description: >-
  "Prilik Writes About Tech" is a blog where Daniel Prilik occationally
  writes interesting and (hopefully) entertaining posts about projects he's
  worked on, or technologies he thought were cool.
baseurl: "/blog"
show_excerpts: true
# twitter_username: danielprilik
github_username: daniel5151
theme: minima
google_analytics: UA-58621690-1
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
sass:
  style: compressed
