title: Thoughts and Projects
author: Daniel Prilik
email: daniel@prilik.com
description: >-
  "Thoughts and Projects" is a collection of interesting and (hopefully)
  entertaining posts and articles written by Daniel Prilik. Typically, he
  writes about projects he's worked on, or technologies that he found cool.
baseurl: "/blog"
show_excerpts: true
# twitter_username: danielprilik
github_username: daniel5151
theme: minima
google_analytics: UA-58621690-1
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
sass:
  style: compressed
